#############################################################################
# Makefile for building: entities
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  entities.pro
# Template: app
# Command: /home/harjot/Qt5.2.1/5.2.1/gcc_64/bin/qmake -o Makefile entities.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../Qt5.2.1/5.2.1/gcc_64/mkspecs/linux-g++ -I. -I. -I../../Qt5.2.1/5.2.1/gcc_64/include -I../../Qt5.2.1/5.2.1/gcc_64/include/QtGui -I../../Qt5.2.1/5.2.1/gcc_64/include/QtCore -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/harjot/Qt5.2.1/5.2.1/gcc_64 -Wl,-rpath,/home/harjot/Qt5.2.1/5.2.1/gcc_64/lib
LIBS          = $(SUBLIBS) -ldxfrw -L/home/harjot/Qt5.2.1/5.2.1/gcc_64/lib -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/harjot/Qt5.2.1/5.2.1/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = test.cpp \
		write_entities.cpp 
OBJECTS       = test.o \
		write_entities.o
DIST          = ../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/shell-unix.conf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/unix.conf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/linux.conf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/qconfig.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/default_post.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/qt.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/resources.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/moc.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/yacc.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/lex.prf \
		entities.pro \
		entities.pro
QMAKE_TARGET  = entities
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = entities


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: entities.pro ../../Qt5.2.1/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf ../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/shell-unix.conf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/unix.conf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/linux.conf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/qconfig.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/default_post.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/qt.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/resources.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/moc.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/yacc.prf \
		../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/lex.prf \
		entities.pro \
		/home/harjot/Qt5.2.1/5.2.1/gcc_64/lib/libQt5Gui.prl \
		/home/harjot/Qt5.2.1/5.2.1/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile entities.pro
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/spec_pre.prf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/shell-unix.conf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/unix.conf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/linux.conf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/gcc-base.conf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/g++-base.conf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/common/g++-unix.conf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/qconfig.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/qt_functions.prf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/qt_config.prf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/spec_post.prf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/default_pre.prf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/resolve_config.prf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/default_post.prf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/warn_on.prf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/qt.prf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/resources.prf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/moc.prf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/unix/opengl.prf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/unix/thread.prf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/exceptions.prf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/yacc.prf:
../../Qt5.2.1/5.2.1/gcc_64/mkspecs/features/lex.prf:
entities.pro:
/home/harjot/Qt5.2.1/5.2.1/gcc_64/lib/libQt5Gui.prl:
/home/harjot/Qt5.2.1/5.2.1/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile entities.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/entities1.0.0 || mkdir -p .tmp/entities1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/entities1.0.0/ && $(COPY_FILE) --parents dxfrw_intf.h write_entities.h .tmp/entities1.0.0/ && $(COPY_FILE) --parents test.cpp write_entities.cpp .tmp/entities1.0.0/ && (cd `dirname .tmp/entities1.0.0` && $(TAR) entities1.0.0.tar entities1.0.0 && $(COMPRESS) entities1.0.0.tar) && $(MOVE) `dirname .tmp/entities1.0.0`/entities1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/entities1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

test.o: test.cpp write_entities.h \
		dxfrw_intf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test.o test.cpp

write_entities.o: write_entities.cpp write_entities.h \
		dxfrw_intf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o write_entities.o write_entities.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

